import React from 'react';
import { AnalysisResult } from '../types';
import { ScoreChart } from './ScoreChart';
import { DimensionChart } from './DimensionChart';
import { BookOpen, Hammer, ArrowRight, GitBranch } from 'lucide-react';

interface ResultCardProps {
  data: AnalysisResult;
}

export const ResultCard: React.FC<ResultCardProps> = ({ data }) => {
  return (
    <div className="bg-white rounded-3xl shadow-xl border border-gray-100 overflow-hidden animate-fade-in-up">
      {/* Top Banner */}
      <div className="bg-slate-900 text-white px-8 py-6 flex flex-col md:flex-row items-center justify-between">
        <div>
          <div className="flex items-center gap-2 opacity-80 mb-1">
            <GitBranch className="w-4 h-4" />
            <span className="text-xs uppercase tracking-widest font-semibold">Repository Analysis</span>
          </div>
          <h2 className="text-2xl md:text-3xl font-bold truncate max-w-lg">
            {data.repository_name}
          </h2>
        </div>
        <div className="mt-4 md:mt-0 px-4 py-1 bg-white/10 rounded-full text-sm font-medium backdrop-blur-sm border border-white/10">
          Generated by GitGrade AI
        </div>
      </div>

      <div className="grid lg:grid-cols-3 gap-0 divide-y lg:divide-y-0 lg:divide-x divide-gray-100">
        
        {/* Column 1: Score & Metrics */}
        <div className="p-8 lg:col-span-1 bg-gray-50/50 flex flex-col">
          <div className="mb-8">
            <h3 className="text-lg font-bold text-gray-800 mb-6">Overall Grade</h3>
            <ScoreChart score={data.score} level={data.level} />
          </div>

          <div className="flex-1 flex flex-col">
            <h4 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-4 text-center">Dimension Profile</h4>
            <div className="flex-1 flex items-center justify-center">
                {/* Safe check for breakdown */}
                {data.breakdown && (
                <DimensionChart data={data.breakdown} />
                )}
            </div>
          </div>
        </div>

        {/* Column 2 & 3: Summary & Roadmap */}
        <div className="lg:col-span-2 p-8">
          
          {/* Summary Section */}
          <div className="mb-10">
            <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-blue-100 flex items-center justify-center text-blue-600">
                <BookOpen className="w-5 h-5" />
              </span>
              Executive Summary
            </h3>
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-5 text-gray-700 leading-relaxed">
              {data.summary}
            </div>
          </div>

          {/* Roadmap Section */}
          <div>
            <h3 className="text-xl font-bold text-gray-800 mb-6 flex items-center gap-2">
              <span className="w-8 h-8 rounded-lg bg-purple-100 flex items-center justify-center text-purple-600">
                <Hammer className="w-5 h-5" />
              </span>
              Personalized Roadmap
            </h3>
            
            <div className="space-y-4">
              {data.roadmap.map((item, index) => (
                <div key={index} className="flex group">
                  <div className="flex flex-col items-center mr-4">
                    <div className="w-8 h-8 rounded-full border-2 border-purple-200 bg-white flex items-center justify-center text-sm font-bold text-purple-600 group-hover:border-purple-500 group-hover:bg-purple-50 transition-colors">
                      {index + 1}
                    </div>
                    {index !== data.roadmap.length - 1 && (
                      <div className="w-0.5 h-full bg-gray-100 my-1 group-hover:bg-purple-100 transition-colors"></div>
                    )}
                  </div>
                  <div className="bg-white border border-gray-200 rounded-xl p-4 flex-1 shadow-sm hover:shadow-md hover:border-purple-200 transition-all cursor-default">
                    <div className="flex items-start justify-between gap-4">
                      <p className="text-gray-700 font-medium">{item}</p>
                      <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-purple-400 mt-1" />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};